### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [gkiely/BatchJS#1]
proper select->insert approach for this: https://github.com/gkiely/Batch/blob/c57398a184c8aeaee457620964cd0b3727778619/index.js#L165

can be found here: [select->insert](https://github.com/vitaly-t/pg-promise/blob/master/examples/select-insert.md) ;)

**Comment by gkiely** [comment]
Thanks for the feedback, but I'm not sure I follow?

**Comment by vitaly-t** [comment]
Sorry, I thought it was a reverse logic - insert, if not found, but on the second read i can see it is insert if found. Anyhow, that example shows nice way of chaining such two queries ;)

https://github.com/vitaly-t/pg-promise/blob/master/examples/select-insert.md

Ops, I didn't even paste the link correctly that time, my bad :)

**Comment by gkiely** [comment]
All good, thanks for the example. It will likely come in handy :+1:
